version: '3'


services:
  server:
          build: ./server
          expose:
              - 5000
          ports:
              - 5000:5000
          volumes:
              - ./server:/srv/app/admin-server
          depends_on:
              - mongo    
          command: npm run start
  client:
        build: ./client
        expose:
            - 3000   
        ports:
            - 80:3000
        volumes:
            - ./client/src:/srv/app/admin-client/src
            - ./client/public:/srv/app/admin-client/public
        stdin_open: true
        command: npm run start          
  mongo:
          image: mongo
          ports:
              - "27017:27017"        